CREATE TABLE students (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) UNIQUE
);

CREATE TABLE marks (
    id SERIAL PRIMARY KEY,
    st_id INTEGER NOT NULL,
    subject VARCHAR(100) NOT NULL,
    marks INTEGER,
    FOREIGN KEY (st_id) REFERENCES students(id) ON DELETE CASCADE
);

